name: Fundamentos_Natan
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - beautifulsoup4
  - requests
  - selenium
  - pandas
  - matplotlib
  - geckodriver
  - pyarrow
  - dateutil.parser 
  - datetime